name: almohsen_3akarat
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  get: ^4.6.6
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  google_sign_in: ^5.0.7
  flutter_login_facebook: ^1.6.2
  flutter_rating_bar: ^4.0.1
  pin_code_fields: ^8.0.1
  country_pickers: ^2.0.0
  smooth_page_indicator: ^1.1.0
  grouped_list: ^5.1.2
  easy_date_timeline: ^1.0.2
  google_maps_flutter: ^2.5.0
  carousel_slider: ^4.2.1
  sms_autofill: ^2.3.0
  intl: ^0.19.0
  fluttertoast: ^8.2.4
  permission_handler: ^11.1.0
  images_picker: ^1.2.11
  flutter_contacts: ^1.1.7+1
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Manrope
      fonts: 
        - asset: assets/fonts/ManropeExtraBold.ttf
          weight: 800
        - asset: assets/fonts/ManropeMedium.ttf
          weight: 500
        - asset: assets/fonts/ManropeBold.ttf
          weight: 700
        - asset: assets/fonts/Manrope.ttf
          weight: 400
        - asset: assets/fonts/ManropeSemiBold.ttf
          weight: 600
        - asset: assets/fonts/ManropeRegular.ttf
          weight: 400
    - family: Readex Pro
      fonts: 
        - asset: assets/fonts/ReadexProRegular.ttf
          weight: 400
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
