import 'controller/settings_controller.dart';import 'package:almohsen_3akarat/core/app_export.dart';import 'package:almohsen_3akarat/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:almohsen_3akarat/widgets/app_bar/appbar_subtitle_two.dart';import 'package:almohsen_3akarat/widgets/app_bar/custom_app_bar.dart';import 'package:almohsen_3akarat/widgets/custom_switch.dart';import 'package:flutter/material.dart';class SettingsScreen extends GetWidget<SettingsController> {const SettingsScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 26.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_application_settings".tr, style: CustomTextStyles.titleSmallBluegray500), SizedBox(height: 14.v), _buildNotificationRow(), SizedBox(height: 16.v), Divider(), SizedBox(height: 15.v), _buildDarkModeRow(), SizedBox(height: 16.v), Divider(), SizedBox(height: 15.v), _buildCountryRow(countryName: "lbl_language".tr, selectedCountry: "lbl_english".tr), SizedBox(height: 16.v), Divider(), SizedBox(height: 15.v), _buildCountryRow(countryName: "lbl_country".tr, selectedCountry: "lbl_us".tr), SizedBox(height: 33.v), Text("lbl_support".tr, style: CustomTextStyles.titleSmallBluegray500), SizedBox(height: 14.v), _buildPrivacyPolicyRow(privacyPolicyText: "lbl_terms_of_use".tr), SizedBox(height: 16.v), Divider(), SizedBox(height: 15.v), _buildPrivacyPolicyRow(privacyPolicyText: "lbl_privacy_policy".tr), SizedBox(height: 14.v), Divider(), SizedBox(height: 15.v), _buildPrivacyPolicyRow(privacyPolicyText: "lbl_about".tr), SizedBox(height: 15.v), Divider(), SizedBox(height: 15.v), _buildPrivacyPolicyRow(privacyPolicyText: "lbl_faqs".tr), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 64.h, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowLeftPrimarycontainer, margin: EdgeInsets.only(left: 24.h, top: 8.v, bottom: 8.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitleTwo(text: "lbl_settings".tr), styleType: Style.bgFill); } 
/// Section Widget
Widget _buildNotificationRow() { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 2.v, bottom: 1.v), child: Text("lbl_notification".tr, style: theme.textTheme.titleSmall)), Obx(() => CustomSwitch(value: controller.isSelectedSwitch.value, onChange: (value) {controller.isSelectedSwitch.value = value;}))]); } 
/// Section Widget
Widget _buildDarkModeRow() { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 2.v, bottom: 1.v), child: Text("lbl_dark_mode".tr, style: theme.textTheme.titleSmall)), Obx(() => CustomSwitch(value: controller.isSelectedSwitch1.value, onChange: (value) {controller.isSelectedSwitch1.value = value;}))]); } 
/// Common widget
Widget _buildCountryRow({required String countryName, required String selectedCountry, }) { return Row(children: [Padding(padding: EdgeInsets.only(top: 2.v), child: Text(countryName, style: theme.textTheme.titleSmall!.copyWith(color: theme.colorScheme.primaryContainer))), Spacer(), Text(selectedCountry, style: CustomTextStyles.titleSmallBluegray500_1.copyWith(color: appTheme.blueGray500)), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(left: 4.h, bottom: 2.v))]); } 
/// Common widget
Widget _buildPrivacyPolicyRow({required String privacyPolicyText}) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 2.v), child: Text(privacyPolicyText, style: theme.textTheme.titleSmall!.copyWith(color: theme.colorScheme.primaryContainer))), CustomImageView(imagePath: ImageConstant.imgArrowRightBlueGray500, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(bottom: 2.v))]); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
/// Navigates to the faqsGetHelpScreen when the action is triggered.
onTapPrivacyPolicyRow() { Get.toNamed(AppRoutes.faqsGetHelpScreen, ); } 
 }
