import 'controller/verify_phone_number_controller.dart';import 'package:almohsen_3akarat/core/app_export.dart';import 'package:almohsen_3akarat/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:almohsen_3akarat/widgets/app_bar/custom_app_bar.dart';import 'package:almohsen_3akarat/widgets/custom_elevated_button.dart';import 'package:almohsen_3akarat/widgets/custom_pin_code_text_field.dart';import 'package:flutter/material.dart';class VerifyPhoneNumberScreen extends GetWidget<VerifyPhoneNumberController> {const VerifyPhoneNumberScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 23.h, vertical: 26.v), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 1.h), child: Text("msg_verify_phone_number".tr, style: theme.textTheme.headlineSmall))), SizedBox(height: 7.v), Align(alignment: Alignment.centerLeft, child: Container(width: 299.h, margin: EdgeInsets.only(left: 1.h, right: 28.h), child: RichText(text: TextSpan(children: [TextSpan(text: "msg_we_send_a_code_to2".tr, style: CustomTextStyles.titleSmallff74778b_1), TextSpan(text: "msg_783_enter".tr, style: CustomTextStyles.titleSmallff16161a)]), textAlign: TextAlign.left))), SizedBox(height: 47.v), Padding(padding: EdgeInsets.only(left: 1.h), child: Obx(() => CustomPinCodeTextField(context: Get.context!, controller: controller.otpController.value, onChanged: (value) {}))), SizedBox(height: 33.v), Text("lbl_resend_code".tr, style: CustomTextStyles.titleMediumPrimarySemiBold), SizedBox(height: 50.v), CustomElevatedButton(text: "lbl_confrim".tr, onPressed: () {onTapConfrim();}), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: double.maxFinite, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowLeftPrimarycontainer, margin: EdgeInsets.fromLTRB(24.h, 8.v, 311.h, 8.v), onTap: () {onTapArrowLeft();}), styleType: Style.bgFill); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
/// Navigates to the selectVirtualAppScreen when the action is triggered.
onTapConfrim() { Get.toNamed(AppRoutes.selectVirtualAppScreen, ); } 
 }
