import 'controller/my_home_empty_controller.dart';import 'package:almohsen_3akarat/core/app_export.dart';import 'package:almohsen_3akarat/presentation/home_page/home_page.dart';import 'package:almohsen_3akarat/presentation/home_search_page/home_search_page.dart';import 'package:almohsen_3akarat/presentation/message_page/message_page.dart';import 'package:almohsen_3akarat/presentation/my_home_page/my_home_page.dart';import 'package:almohsen_3akarat/presentation/profile_page/profile_page.dart';import 'package:almohsen_3akarat/widgets/custom_bottom_bar.dart';import 'package:almohsen_3akarat/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';class MyHomeEmptyScreen extends GetWidget<MyHomeEmptyController> {const MyHomeEmptyScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 25.h), child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 7.v), CustomImageView(imagePath: ImageConstant.imgFrame, height: 255.adaptSize, width: 255.adaptSize), SizedBox(height: 63.v), Text("msg_ready_to_sell_your".tr, style: theme.textTheme.titleLarge), SizedBox(height: 6.v), SizedBox(width: 324.h, child: Text("msg_relax_is_making".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: theme.textTheme.bodyLarge!.copyWith(height: 1.50))), SizedBox(height: 22.v), CustomElevatedButton(height: 45.v, width: 155.h, text: "lbl_add_proprty".tr, onPressed: () {onTapAddProprty();})])), bottomNavigationBar: _buildBottomBar())); } 
/// Section Widget
Widget _buildBottomBar() { return CustomBottomBar(onChanged: (BottomBarEnum type) {Get.toNamed(getCurrentRoute(type), id: 1);}); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Home: return AppRoutes.homePage; case BottomBarEnum.Message: return AppRoutes.messagePage; case BottomBarEnum.Discover: return AppRoutes.homeSearchPage; case BottomBarEnum.Myhome: return AppRoutes.myHomePage; case BottomBarEnum.Profile: return AppRoutes.profilePage; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(String currentRoute) { switch (currentRoute) {case AppRoutes.homePage: return HomePage(); case AppRoutes.messagePage: return MessagePage(); case AppRoutes.homeSearchPage: return HomeSearchPage(); case AppRoutes.myHomePage: return MyHomePage(); case AppRoutes.profilePage: return ProfilePage(); default: return DefaultWidget();} } 
/// Navigates to the homeContainerScreen when the action is triggered.
onTapAddProprty() { Get.toNamed(AppRoutes.homeContainerScreen, ); } 
 }
