import 'controller/add_new_property_home_facts_controller.dart';import 'package:almohsen_3akarat/core/app_export.dart';import 'package:almohsen_3akarat/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:almohsen_3akarat/widgets/app_bar/appbar_subtitle_two.dart';import 'package:almohsen_3akarat/widgets/app_bar/custom_app_bar.dart';import 'package:almohsen_3akarat/widgets/custom_drop_down.dart';import 'package:almohsen_3akarat/widgets/custom_elevated_button.dart';import 'package:almohsen_3akarat/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';class AddNewPropertyHomeFactsScreen extends GetWidget<AddNewPropertyHomeFactsController> {const AddNewPropertyHomeFactsScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 24.v), Expanded(child: SingleChildScrollView(child: Container(margin: EdgeInsets.only(bottom: 5.v), padding: EdgeInsets.symmetric(horizontal: 23.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildAddressAndProgress(), SizedBox(height: 16.v), Padding(padding: EdgeInsets.only(left: 1.h), child: Container(height: 6.v, width: 327.h, decoration: BoxDecoration(color: appTheme.gray300, borderRadius: BorderRadius.circular(3.h)), child: ClipRRect(borderRadius: BorderRadius.circular(3.h), child: LinearProgressIndicator(value: 0.75, backgroundColor: appTheme.gray300, valueColor: AlwaysStoppedAnimation<Color>(theme.colorScheme.primary))))), SizedBox(height: 24.v), Padding(padding: EdgeInsets.only(left: 1.h), child: Text("lbl_home_facts".tr, style: CustomTextStyles.titleMediumBold_1)), SizedBox(height: 9.v), Container(width: 321.h, margin: EdgeInsets.only(left: 1.h, right: 6.h), child: Text("msg_this_helps_your".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.bodySmall!.copyWith(height: 1.50))), SizedBox(height: 16.v), Padding(padding: EdgeInsets.only(left: 1.h), child: Text("lbl_type_property".tr, style: theme.textTheme.labelLarge)), SizedBox(height: 6.v), Padding(padding: EdgeInsets.only(left: 1.h), child: CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 14.v, 14.h, 14.v), child: CustomImageView(imagePath: ImageConstant.imgArrowdownPrimarycontainer, height: 20.adaptSize, width: 20.adaptSize)), hintText: "lbl_select_type".tr, hintStyle: CustomTextStyles.titleSmallBluegray500Medium, items: controller.addNewPropertyHomeFactsModelObj.value.dropdownItemList!.value, borderDecoration: DropDownStyleHelper.fillGray, fillColor: appTheme.gray300, onChanged: (value) {controller.onSelected(value);})), SizedBox(height: 13.v), _buildInputs1(), SizedBox(height: 17.v), _buildInputs2(), SizedBox(height: 17.v), _buildTitle5(), SizedBox(height: 18.v), Padding(padding: EdgeInsets.only(left: 1.h), child: Text("lbl_monthly_rent".tr, style: theme.textTheme.labelLarge)), SizedBox(height: 6.v), Padding(padding: EdgeInsets.only(left: 1.h), child: CustomTextFormField(controller: controller.priceController1, hintText: "lbl_02".tr, textInputAction: TextInputAction.done))]))))])), bottomNavigationBar: _buildBtn())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 64.h, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowLeftPrimarycontainer, margin: EdgeInsets.only(left: 24.h, top: 8.v, bottom: 8.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitleTwo(text: "msg_add_new_property".tr), styleType: Style.bgFill); } 
/// Section Widget
Widget _buildAddressAndProgress() { return Padding(padding: EdgeInsets.only(left: 1.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.symmetric(vertical: 6.v), child: Text("lbl_home_facts".tr, style: theme.textTheme.titleSmall)), CustomElevatedButton(height: 33.v, width: 79.h, text: "lbl_06_08".tr, buttonStyle: CustomButtonStyles.fillPrimaryTL16, buttonTextStyle: CustomTextStyles.titleSmallWhiteA700)])); } 
/// Section Widget
Widget _buildInputs1() { return Padding(padding: EdgeInsets.only(left: 1.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: Padding(padding: EdgeInsets.only(right: 6.h), child: Column(children: [_buildTitle1(fullBaths: "msg_finished_sq_ft".tr), SizedBox(height: 6.v), CustomTextFormField(width: 158.h, controller: controller.inputFieldsController, hintText: "lbl_0".tr)]))), Expanded(child: Padding(padding: EdgeInsets.only(left: 6.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_lot_size".tr, style: theme.textTheme.labelLarge), SizedBox(height: 7.v), CustomTextFormField(width: 158.h, controller: controller.inputFieldsController1, hintText: "lbl_0".tr)])))])); } 
/// Section Widget
Widget _buildInputs2() { return Padding(padding: EdgeInsets.only(left: 1.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: Padding(padding: EdgeInsets.only(right: 6.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_year_built".tr, style: theme.textTheme.labelLarge), SizedBox(height: 7.v), CustomTextFormField(width: 158.h, controller: controller.inputFieldsController2, hintText: "lbl_0".tr)]))), Expanded(child: Padding(padding: EdgeInsets.only(left: 6.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_bedrooms".tr, style: theme.textTheme.labelLarge), SizedBox(height: 7.v), CustomTextFormField(width: 158.h, controller: controller.inputFieldsController3, hintText: "lbl_0".tr)])))])); } 
/// Section Widget
Widget _buildTitle5() { return Padding(padding: EdgeInsets.only(left: 1.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: Padding(padding: EdgeInsets.only(right: 6.h), child: Column(children: [_buildTitle1(fullBaths: "lbl_full_baths".tr), SizedBox(height: 7.v), CustomTextFormField(width: 158.h, controller: controller.inputFieldsController4, hintText: "lbl_0".tr)]))), Expanded(child: Padding(padding: EdgeInsets.only(left: 6.h), child: Column(children: [_buildTitle1(fullBaths: "msg_security_deposit".tr), SizedBox(height: 6.v), CustomTextFormField(width: 158.h, controller: controller.priceController, hintText: "lbl_02".tr)])))])); } 
/// Section Widget
Widget _buildBtn() { return Container(margin: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 24.v), decoration: AppDecoration.outlineBlueGrayF, child: CustomElevatedButton(text: "lbl_next".tr, onPressed: () {onTapNext();})); } 
/// Common widget
Widget _buildTitle1({required String fullBaths}) { return SizedBox(width: 158.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text(fullBaths, style: theme.textTheme.labelLarge!.copyWith(color: appTheme.blueGray500)), CustomImageView(imagePath: ImageConstant.imgVideoCamera, height: 16.adaptSize, width: 16.adaptSize)])); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
/// Navigates to the addNewPropertyContactScreen when the action is triggered.
onTapNext() { Get.toNamed(AppRoutes.addNewPropertyContactScreen, ); } 
 }
