import '../filter_page/widgets/optionschipview_item_widget.dart';import '../filter_page/widgets/propertytypechipview_item_widget.dart';import 'controller/filter_controller.dart';import 'models/filter_model.dart';import 'models/optionschipview_item_model.dart';import 'models/propertytypechipview_item_model.dart';import 'package:almohsen_3akarat/core/app_export.dart';import 'package:almohsen_3akarat/widgets/custom_drop_down.dart';import 'package:almohsen_3akarat/widgets/custom_elevated_button.dart';import 'package:almohsen_3akarat/widgets/custom_icon_button.dart';import 'package:almohsen_3akarat/widgets/custom_outlined_button.dart';import 'package:flutter/material.dart';
// ignore_for_file: must_be_immutable
class FilterPage extends StatelessWidget {FilterPage({Key? key}) : super(key: key);

FilterController controller = Get.put(FilterController(FilterModel().obs));

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(child: Column(children: [SizedBox(height: 27.v), Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildTitleAndPrice(), SizedBox(height: 22.v), _buildLineStack(), SizedBox(height: 25.v), Padding(padding: EdgeInsets.only(left: 24.h), child: Text("lbl_features".tr, style: CustomTextStyles.titleMedium16)), SizedBox(height: 20.v), Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: _buildBathsRow(bathsText: "lbl_beds".tr, twoText: "lbl_42".tr)), SizedBox(height: 16.v), Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: _buildBathsRow(bathsText: "lbl_baths".tr, twoText: "lbl_2".tr)), SizedBox(height: 27.v), Padding(padding: EdgeInsets.only(left: 24.h), child: Text("lbl_property_facts".tr, style: CustomTextStyles.titleMedium16)), SizedBox(height: 17.v), _buildSquareFeetRow(), SizedBox(height: 17.v), Padding(padding: EdgeInsets.only(left: 24.h), child: Text("lbl_lot_size".tr, style: theme.textTheme.titleSmall)), SizedBox(height: 8.v), _buildInputsRow(), SizedBox(height: 27.v), Padding(padding: EdgeInsets.only(left: 24.h), child: Text("lbl_property_type".tr, style: CustomTextStyles.titleMedium16)), SizedBox(height: 14.v), _buildPropertyTypeChipView(), SizedBox(height: 25.v), Padding(padding: EdgeInsets.only(left: 24.h), child: Row(children: [Text("lbl_amenities".tr, style: CustomTextStyles.titleMedium16), CustomImageView(imagePath: ImageConstant.imgVideoCamera, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(left: 26.h))])), SizedBox(height: 16.v), _buildOptionsChipView(), SizedBox(height: 16.v), Padding(padding: EdgeInsets.only(left: 24.h), child: Row(children: [Text("lbl_see_more".tr, style: CustomTextStyles.titleSmallPrimaryBold), CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(left: 8.h, bottom: 2.v))])), SizedBox(height: 24.v), _buildButtonsRow()])]))))); } 
/// Section Widget
Widget _buildTitleAndPrice() { return Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_price_range".tr, style: CustomTextStyles.titleMedium16), Text("lbl_200_15_000".tr, style: CustomTextStyles.titleSmallPrimary_1)]))); } 
/// Section Widget
Widget _buildLineStack() { return Align(alignment: Alignment.center, child: SizedBox(height: 24.v, width: 327.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.only(bottom: 7.v), child: SizedBox(width: 327.h, child: Divider(color: appTheme.gray300)))), Align(alignment: Alignment.center, child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [_buildChevronButton(), Padding(padding: EdgeInsets.only(top: 14.v, bottom: 7.v), child: SizedBox(width: 103.h, child: Divider(color: theme.colorScheme.primary))), _buildChevronButton()]))]))); } 
/// Section Widget
Widget _buildSquareFeetColumn() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_square_feet".tr, style: theme.textTheme.titleSmall), SizedBox(height: 6.v), CustomDropDown(width: 139.h, icon: Container(margin: EdgeInsets.fromLTRB(30.h, 14.v, 12.h, 15.v), child: CustomImageView(imagePath: ImageConstant.imgArrowdownBlueGray5001, height: 16.adaptSize, width: 16.adaptSize)), hintText: "lbl_min".tr, items: controller.filterModelObj.value.dropdownItemList!.value, onChanged: (value) {controller.onSelected(value);})]); } 
/// Section Widget
Widget _buildSquareFeetRow() { return Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.end, children: [_buildSquareFeetColumn(), CustomImageView(imagePath: ImageConstant.imgArrowDown, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(left: 16.h, top: 41.v, bottom: 13.v)), Padding(padding: EdgeInsets.only(left: 17.h, top: 26.v), child: CustomDropDown(width: 139.h, icon: Container(margin: EdgeInsets.fromLTRB(30.h, 14.v, 12.h, 15.v), child: CustomImageView(imagePath: ImageConstant.imgArrowdownBlueGray5001, height: 16.adaptSize, width: 16.adaptSize)), hintText: "lbl_max".tr, items: controller.filterModelObj.value.dropdownItemList1!.value, onChanged: (value) {controller.onSelected1(value);}))]))); } 
/// Section Widget
Widget _buildInputsRow() { return Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomDropDown(width: 139.h, icon: Container(margin: EdgeInsets.fromLTRB(30.h, 14.v, 12.h, 15.v), child: CustomImageView(imagePath: ImageConstant.imgArrowdownBlueGray5001, height: 16.adaptSize, width: 16.adaptSize)), hintText: "lbl_min".tr, items: controller.filterModelObj.value.dropdownItemList2!.value, onChanged: (value) {controller.onSelected2(value);}), CustomImageView(imagePath: ImageConstant.imgArrowDown, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(left: 16.h, top: 15.v, bottom: 14.v)), Padding(padding: EdgeInsets.only(left: 17.h), child: CustomDropDown(width: 139.h, icon: Container(margin: EdgeInsets.fromLTRB(30.h, 14.v, 12.h, 15.v), child: CustomImageView(imagePath: ImageConstant.imgArrowdownBlueGray5001, height: 16.adaptSize, width: 16.adaptSize)), hintText: "lbl_max".tr, items: controller.filterModelObj.value.dropdownItemList3!.value, onChanged: (value) {controller.onSelected3(value);}))]))); } 
/// Section Widget
Widget _buildPropertyTypeChipView() { return Align(alignment: Alignment.center, child: Obx(() => Wrap(runSpacing: 8.v, spacing: 8.h, children: List<Widget>.generate(controller.filterModelObj.value.propertytypechipviewItemList.value.length, (index) {PropertytypechipviewItemModel model = controller.filterModelObj.value.propertytypechipviewItemList.value[index]; return PropertytypechipviewItemWidget(model);})))); } 
/// Section Widget
Widget _buildOptionsChipView() { return Padding(padding: EdgeInsets.only(left: 24.h), child: Obx(() => Wrap(runSpacing: 8.v, spacing: 8.h, children: List<Widget>.generate(controller.filterModelObj.value.optionschipviewItemList.value.length, (index) {OptionschipviewItemModel model = controller.filterModelObj.value.optionschipviewItemList.value[index]; return OptionschipviewItemWidget(model);})))); } 
/// Section Widget
Widget _buildButtonsRow() { return Container(width: double.maxFinite, padding: EdgeInsets.all(24.h), decoration: AppDecoration.outlineBlueGrayF, child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: CustomOutlinedButton(text: "lbl_reset".tr, margin: EdgeInsets.only(right: 7.h), buttonStyle: CustomButtonStyles.outlinePrimaryTL10, buttonTextStyle: CustomTextStyles.titleMediumPrimaryBold)), Expanded(child: CustomElevatedButton(text: "lbl_apply".tr, margin: EdgeInsets.only(left: 7.h)))])); } 
/// Common widget
Widget _buildChevronButton() { return Container(width: 24.h, padding: EdgeInsets.symmetric(horizontal: 3.h, vertical: 7.v), decoration: AppDecoration.fillPrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder5), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgChevronLeft, height: 10.adaptSize, width: 10.adaptSize), CustomImageView(imagePath: ImageConstant.imgChevronRight, height: 10.adaptSize, width: 10.adaptSize)])); } 
/// Common widget
Widget _buildBathsRow({required String bathsText, required String twoText, }) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text(bathsText, style: CustomTextStyles.titleMediumMedium.copyWith(color: theme.colorScheme.primaryContainer)), Spacer(), CustomIconButton(height: 24.adaptSize, width: 24.adaptSize, child: CustomImageView(imagePath: ImageConstant.imgArrowLeftGray300)), Padding(padding: EdgeInsets.only(left: 15.h), child: Text(twoText, style: CustomTextStyles.titleMedium16.copyWith(color: theme.colorScheme.primaryContainer))), Padding(padding: EdgeInsets.only(left: 15.h), child: CustomIconButton(height: 24.adaptSize, width: 24.adaptSize, child: CustomImageView(imagePath: ImageConstant.imgFloatingIcon)))]); } 
 }
